---
cog_bundle_version: 3
name: format
version: 0.2.0
docker:
  image: cogcmd/format
  tag: 0.2.0
commands:
  table:
    executable: /Users/imbriaco/operable/bundles/format-rb/cog-command
    rules: [ 'allow' ]
templates:
  preformatted:
    slack: '```{{ body }}```'
    hipchat: '<pre>{{ body }}</pre>'
