---
cog_bundle_version: 3
name: format
version: 0.1.4
#docker:
#  image: cogcmd/format
#  tag: 0.1.4
commands:
  table:
    executable: /Users/imbriaco/operable/bundles/format-rb/cog-command
    rules: [ 'allow' ]
templates:
  preformatted:
    slack: '```{{ body }}```'
    hipchat: '<pre>{{ body }}</pre>'
