steps:
  - label: ":rspec: Unit Tests"
    command: bundle exec rspec --format=documentation
    plugins:
      docker-compose:
        run: test
        config: docker-compose.ci.yml

  - wait

  - label: ":cogops: :docker: Build and Push Image"
    plugins:
      "operable/cog-bundle":
        build: config.yaml
        tag: "cogcmd/format-testing:0.5.0-${BUILDKITE_BUILD_NUMBER}-${BUILDKITE_COMMIT}"

  - wait

  - label: ":cogops: Test it in a Cog server!"
    plugins:
      "operable/cog-bundle":
        test: integration.yaml
